In [97]:
import numpy as np
import copy, math
import matplotlib.pyplot as plt
np.set_printoptions(precision=2)

In [126]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

print(f"X shape : {X_train.shape}, X Type: {type(X_train)})")
print(X_train)
print(f"y shape: {y_train.shape}, y type: {type(y_train)})")
print(y_train)

X shape : (3, 4), X Type: <class 'numpy.ndarray'>)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y shape: (3,), y type: <class 'numpy.ndarray'>)
[460 232 178]


In [127]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


#### Prediction using loop

In [128]:
def predict_single_loop(w, x, b):

    n = x.shape[0]
    p = 0

    for i in range(n):
        p_i = x[i] * w[i]
        # print(f"{x[i]} * {w[i]} = {p_i}")
        p += p_i
        # print("running total =", p)

    # print("before bias =", p)
    p += b
    # print("after bias =", p)

    return p


In [129]:
# get a row from our training data
x_vec = X_train[0,:] 
print(f"x_vec shape : {x_vec.shape}, x_vec value: {x_vec}")

# make a prediction 
f_wb = predict_single_loop(w_init, x_vec, b_init)
print(f"f_wb shape {f_wb.shape}, prediction : {f_wb}")

x_vec shape : (4,), x_vec value: [2104    5    1   45]
f_wb shape (), prediction : 459.9999976194083


#### Prediction using dot

In [130]:
def predict(w, x, b):
    """
            single predict using linear regression
    Args:
        x (ndarray): shape(m,n) example with multiple features
        w (ndarray) :shape(n,) model parameter
        b(scalar) : model parameter

    returns:
        p(scalar)
    """
    p = np.dot(x, w) + b
    return p 

In [131]:
x_vec = X_train[0,:]
f_wb = predict (w_init, x_vec, b_init)

print(f"f_wb shape {f_wb.shape}, prediction : {f_wb}")

f_wb shape (), prediction : 459.9999976194083


### Compute cost with multiple variables

The equation for the cost function  with multiple variables $J(\mathbf{w}, b)$ is:
$$J(\mathbf{w}, b) = \frac{1}{2m} \sum\limits_{i = 0}^{m-1} (f_{\mathbf{w}, b}(\mathbf{x}^{(i)}) -y^{(i)})^2 \tag{1}$$
where:
$$ f_{\mathbf{w}, b}(\mathbf{x}^{(i)}) = \mathbf{w} \cdot \mathbf{x}^{i} + b \tag{2} $$

In [132]:
def compute_cost(x, w, b, y) :
    """
        compute cost.
        Args: 
            X (ndarray (m,n)): data, m example and n features
            y (ndarray(m)) : target values
            w (ndarray (n,)) : model parameter
            b (scalar) : model parameter 

        Return :
        cost (scalar): cost
    """
    m = x.shape[0]
    cost = 0.0
    for i in range(m):
        f_wb_i = np.dot(x[i], w) + b
        cost = cost + (f_wb_i - y[i])**2   
    cost = cost / (2 * m) 
    
    return cost

In [133]:
cost = compute_cost(X_train, w_init, b_init, y_train)
print(f"cost at optimal w : {cost}")

cost at optimal w : 1.5578904428966628e-12


### Gradient Descent with multiple variables

Gradienbt descent for multiple variable


In [ ]:
def compute_gradient(X, y, w, b):
    """
    compute the gradient for linear regression
    Args :
        X (ndarray (m,n)) : data, m example, n features
        y (ndarrat (m,)) : target values
        w (ndarray (n,)) : model parameters
        b (scalar) : model parameter
    return :
        dj_dw (ndarray (n,)): gradient of cost w.r.t the parameter w
        df_db (scalar) : gradient of cost w.r.t the parameter b
    """